### ISSUE TITLE
Ability to add existing song to queue

### ISSUE THREAD

**Issue by joshvazquez** [nstbayless/flyweb-mp3#15]
Display cached songs so that they can be added to the queue again without reuploading as a new song.

**Comment by nstbayless** [comment]
I'm not sure this is important; the user interface seems like it could be tricky, and maybe not very useful even. Why not delete songs from the cache if they are not on any playlist?

**Comment by wchae** [comment]
Agree with @nstbayless here. Might even be okay to close this issue.
