### ISSUE TITLE
Code style

### ISSUE THREAD

**Issue by joshvazquez** [nstbayless/flyweb-mp3#16]
I am working on enforcing a consistent style throughout the codebase.

Please watch out for bad stylistic decisions and correct these going forward.

- Inconsistent spacing (around blocks, if-statements, function definitions, operators, etc.)
- Spaces vs. tabs: let's standardize on 4 spaces for this project
- Unbraced if-statements
- Missing semicolons after expressions
- Inconsistent indentation

@nstbayless @wchae @sinoforever 
CC @justindarc @kannanvijayan

**Comment by joshvazquez** [comment]
Made first pass. Feel free to disagree with a style choice if you think there is a better one. I was getting some syntax errors in WebStorm but I don't think those are actual errors. Ran and tested successfully.

Found that .editorconfig doesn't have a lot of options, is there anything else we can use to automatically enforce style?

**Comment by nstbayless** [comment]
I like basically all your style choices, they fit with me. The only thing I found maybe odd was:

```
} else if (...) {
```

became

```
} else
  if (...) {
```

also, for anonymous functions, I find the space after 'function' uncomfortable:

```
function (err, s)
```

But I don't feel strongly about it.

**Comment by joshvazquez** [comment]
> became
>
>```
> } else
>  if (...) {
> ```

In what file did you see that? That must have been an accident, I'll fix it.  
  
For anonymous functions, I found examples of both styles online so I'm OK with either.

**Comment by wchae** [comment]
I'm fine with all the changes.

Another thing to note might be naming conventions - I've seen varying uses of camelcase and underscores.

**Comment by nstbayless** [comment]
Closing this issue due to introduction of linter. While there are some things that are brought up here that the linter won't detect, please continue discussion in #33.
