### ISSUE TITLE
api vs index

### ISSUE THREAD

**Issue by nstbayless** [nstbayless/flyweb-mp3#19]
In [index.js, ll. 63-91](https://github.com/nstbayless/flyweb-mp3/blob/master/routes/index.js#L63-L91), there are several GET calls that return json objects. I feel like these ought to be considered "API" calls and hence they belong in api.js

But we're changing our architecture to use socket.io. So, do we even need an api.js anymore? Perhaps we could have both a RESTful api and sockets?

@sinoforever @wchae the calls in question relate to what you were working on. Thoughts?

**Comment by wchae** [comment]
status, pause, prev, next are no longer needed - safe to remove

**Comment by nstbayless** [comment]
Resolved in 5ff081aa3170c655d2dce7f7e4654ac9bffb59fb
