### ISSUE TITLE
variable name inconsistency for playlists

### ISSUE THREAD

**Issue by nstbayless** [nstbayless/flyweb-mp3#21]
These variables all can refer to the same thing:

`plid`, `list`, `list_id`, `listId`, `l`

These can also refer to the same thing:

`pl`, `list`, `l`

I'm hesitant to adopt `list`/`listId` as the standard term, since there are more types of lists than just playlists.

Proposals (I'm okay with any of these):
- `pl` and `plid`
- `plist` and `plistid`
- `plist` and `plistId`
- `playlist` and `playlistid`
- `playlist` and `playlistId`

I'm hesitant about the -`Id` endings because the case could be confusing. I find `id` and `ID` easiest to remember, but `ID` follows camelCase rules less well.

@joshvazquez

**Comment by joshvazquez** [comment]
I do not recommend unnecessarily making abbreviations out of regular words ("playlist") to make things such as `pl`, `plid`, `plist`. To me, this is unclear and inhibits quick reading. I would suggest following camelCase and using `playlist` and `playlistId` if you are not in favour of `list*`. Although I think in some contexts, the `list*` variant can be just as effective without introducing ambiguity. This could be done in argument lists such as `playlist_manager.getPlaylist = function (list, callback)` where the usage is clear, and maybe or maybe not in class variables. The long name is fine as well.

**Comment by nstbayless** [comment]
Alright, list and listId are fine for me. There are a number of places where list is used where it should be listId; so long as we avoid that I'm happy.

**Comment by joshvazquez** [comment]
Fair point, `getPlaylist()` above is one of those places.

**Comment by nstbayless** [comment]
Changed variable names in front-end and route handlers (14745730a117fda737bd7fd747249f5171fca7a2) so I'm closing this.
