### ISSUE TITLE
index.js -> view.js

### ISSUE THREAD

**Issue by nstbayless** [nstbayless/flyweb-mp3#26]
Would anybody object if I renamed `index.js`? That was just the default name from express, and I don't think it really makes sense (because it handles more than just the index page). I was thinking `view.js` would make more sense, because it handles GET requests that always result in rendering views.

@wchae is probably the other person who deals with views the most

**Comment by wchae** [comment]
I don't think that's enough of a reason to change the name

**Comment by nstbayless** [comment]
ok.
