### ISSUE TITLE
add from URL icon

### ISSUE THREAD

**Issue by nstbayless** [nstbayless/flyweb-mp3#27]
Currently, the "add from a website" icon is the same as the "upload from your device" icon:

![upload icon](https://github.com/nstbayless/flyweb-mp3/blob/master/public/images/add_module_upload.png?raw=true)

This conveys "upload," but this is misleading since adding from a website is not uploading.

Here are some suggestions:
- Make the arrow point down, since the server is "downloading" it from the web
- Use the Firefox logo (since this is FlyWeb, all users for the forseeable future will be using Firefox)
- A generic globe icon
- Youtube's logo

The Youtube logo probably has the most conveyance but is also my least favourite choice, since the logo is trademarked and also it supports other websites as well.

I'm happy to make the icon myself. Any input?

**Comment by sinoforever** [comment]
How about something along this line but free?https://www.iconfinder.com/icons/307765/application_computer_movie_multimedia_play_player_stream_video_icon

**Comment by nstbayless** [comment]
Good idea! I like the "play" button concept.

![add_module_url](https://cloud.githubusercontent.com/assets/7698597/19290228/96e7ab04-8fc3-11e6-8245-5f238b423fce.png)

How's this look

**Comment by sinoforever** [comment]
I think a play button is great, youtube is sort of symbolized by the play button and we want button for youtube.

**Comment by nstbayless** [comment]
![add_module_url_with_streamer](https://cloud.githubusercontent.com/assets/7698597/19290417/784a6a3c-8fc4-11e6-845f-71c4cb06cee5.png)

The streamer makes it more clear, perhaps.

**Comment by nstbayless** [comment]
implemented in  29c491a

**Comment by wchae** [comment]
Change has been reverted in commit https://github.com/nstbayless/flyweb-mp3/commit/49351052105c798fb3e6278cb3d43e6f5cfd5beb

**Comment by nstbayless** [comment]
Why was it reverted?

**Comment by wchae** [comment]
Accidental rewrite by Josh

**Comment by nstbayless** [comment]
@joshvazquez 

re-added the add module url icon. a30852e0ce3fe729da380e5876f7be06ed8ed2b8
