### ISSUE TITLE
Server crashes with "Illegal instruction: 4" when switching songs

### ISSUE THREAD

**Issue by kannanvijayan** [nstbayless/flyweb-mp3#29]
Happens on my mac when I try it out.  When the playlist switches from first song to next, or when we try to manually switch using the "next song" icon, the server crashes displaying the message "Illegal instruction: 4".  I updated to the latest node.js and it's still happening.  Previous version was 5.6.0, current version is 6.7.0.

If there is no direct resolution to this in the code (if it's an internal node issue), then the workaround for it should be identified and added to the instructions.

**Comment by sinoforever** [comment]
Happens on my mac too, but not on Linux machines. I have no idea how to fix it, I'll think of a workaround.

**Comment by sinoforever** [comment]
fixed in 45e646a
