### ISSUE TITLE
playlist update in sockets

### ISSUE THREAD

**Issue by nstbayless** [nstbayless/flyweb-mp3#30]
Right now it's by GET polling. Should update playlist in client via websockets.

**Comment by nstbayless** [comment]
Implemented in ed6e147f3a15738b33ffe33a0ba8a8e8acd4a912. Pull request to come.

**Comment by nstbayless** [comment]
@wchae 

I'd like to point out that, within five minutes of each other, we both implemented the same code?

**Comment by nstbayless** [comment]
@wchae your implementation is based in audiojs. this is the wrong place for it, it should be in playlist_manager.

**Comment by wchae** [comment]
ok, just go ahead and merge yours in

**Comment by nstbayless** [comment]
okay, I'm requesting a lock for the next, say, ten minutes.

**Comment by nstbayless** [comment]
My commit c052f92334f4d6beee69d0e8d7f6a7fdcde6007d, committed at 20:35, is up-to-date with your commit 63b65fa7b282018151f6b2ce550f867a9357d52d, commited at 19:31 (but listed as 23:31, for some reason? I think your clock is off.). In other words, I've already merged with most of your recent work.

The commits you made afterward are roughly analogous, except that my emits occur from playlist manager, which I think is the correct one.

My proposal: let master point to my commit c052f92334f4d6beee69d0e8d7f6a7fdcde6007d

**Comment by nstbayless** [comment]
@wchae: what's your opinion? Do I have permission to do this? The resulting changes are fairly minor, I think, but it could cause git to hiccup for you if you aren't aware of it.

**Comment by nstbayless** [comment]
Okay, I merged it into master, no commits were lost. 15d0719b06f0ddac5d771374d4d15806
