### ISSUE TITLE
Clean up for lint

### ISSUE THREAD

**Issue by nstbayless** [nstbayless/flyweb-mp3#33]
@justindarc added a linter in 1c6fde9a4c87d5395b53ba9a27687f9d3a17d40c

Please list yourself in this issue before you take it upon yourself to clean up a file. Do _not_ clean a file without listing yourself here (and checking to see the file is not already taken).

Lack of communication --> merging headaches. :)

@wchae @joshvazquez @sinoforever @nstbayless

List of files not yet cleaned: https://github.com/nstbayless/flyweb-mp3/blob/master/.jshintignore

**Comment by joshvazquez** [comment]
I'll update the linter rules when I get a chance.

**Comment by nstbayless** [comment]
src/audio_manager.js

**Comment by nstbayless** [comment]
All files clean: https://github.com/nstbayless/flyweb-mp3/commit/579524a8136547f548bad5409bd8a82d151915ba
