### ISSUE TITLE
Custom name getting overwritten on npm start

### ISSUE THREAD

**Issue by wchae** [nstbayless/flyweb-mp3#38]
Steps to reproduce:

1. Edit config.json as follows: `{"defaults":{"name":"Test Name"}}`
2. run `npm start` in the flyweb-mp3 directory.
3. Name of node app is "Local Area mp3" rather than "Test Name".

**Comment by nstbayless** [comment]
>_> this config keeps causing problems, I'll look into it. Sorry :|

**Comment by nstbayless** [comment]
resolved as of c585329ef987633eee043d2521ee07f4247

[offending line](https://github.com/nstbayless/flyweb-mp3/commit/c585329ef987633eee043d2521ee07f42477759a#diff-731ce67b643e6620e04781e9683be0d9L16):

```
fs.statSync("../" + config_file).isFile();
```

`"../" +` removed.
