### ISSUE TITLE
ffmpeg -> avconv

### ISSUE THREAD

**Issue by nstbayless** [nstbayless/flyweb-mp3#39]
`ffmpeg` is dying, `avconv` should be used instead.

(It uses exactly the same command line syntax, but I'm not sure how we're accessing ffmpeg from node anyway.)

@joshvazquez

**Comment by nstbayless** [comment]
I noticed that if one as `avconv` installed, the program uses that just fine. So maybe we should just change the README to say use `avconv` instead of `ffmpeg`

**Comment by joshvazquez** [comment]
@nstbayless it worked with only avconv installed and not ffmpeg?

**Comment by nstbayless** [comment]
The raspberry pi is able to convert videos only after I installed avconv. `ffmpeg` is not installed on my raspberry pi, and `avconv` is. Just checked.

**Comment by joshvazquez** [comment]
Great! The youtube-dl package uses whichever available one then. All we have to change is the readme. df29fe8
