### ISSUE TITLE
Allow random-access seeking in songs using the progress bar UI element.

### ISSUE THREAD

**Issue by kannanvijayan** [nstbayless/flyweb-mp3#40]
If a listener wants to move to an arbitrary point in the song, they should be able to click/touch a point in the progress bar to move to that location.

**Comment by wchae** [comment]
Added basic functionality in https://github.com/nstbayless/flyweb-mp3/commit/4b6c866c58e06daec11fbc69392a97883e194e72. Additional features may include dragging a button.

**Comment by wchae** [comment]
Added circular handle in https://github.com/nstbayless/flyweb-mp3/commit/4a8f67cd771b13962c895ff8c9f7547d0f4e33ab.
