### ISSUE TITLE
Sockets break on 'back'

### ISSUE THREAD

**Issue by nstbayless** [nstbayless/flyweb-mp3#48]
@wchae 

After using the 'back' button, live updates no longer occur. Do you know if this might be fixable? I don't 100% understand web sockets yet.

Thanks :)

**Comment by wchae** [comment]
Seems to be working for the most part. The only bug I see is with the highlighting of the song name, which I fixed just now in https://github.com/nstbayless/flyweb-mp3/commit/e4011906fc7b13f5b949bb3948621ad24d1f858f.

**Comment by wchae** [comment]
Added list updating in https://github.com/nstbayless/flyweb-mp3/commit/66a09bda5eb44a28873fe0cc1b380cb25404bc0b.
