### ISSUE TITLE
sockets.js injection

### ISSUE THREAD

**Issue by nstbayless** [nstbayless/flyweb-mp3#55]
@wchae,

Currently, the socket io object is injected into sockets.js in a way that makes it impossible to include socket.js via `require`, so other files that need it have to have the socket.js require from `app.js` injected into them... it's a bit complicated. 

Proposed solution: expose a setter function from `socket.js` to allow `app.js` or `www` to include it and then give it the socket io object, but also allow other things to include `socket.js` without providing an object too.

What do you think? (I can fix this if you like.)

**Comment by wchae** [comment]
Sure, as long as it doesn't break any existing features.
