### ISSUE TITLE
Too easy to accidentally sort songs on mobile

### ISSUE THREAD

**Issue by wchae** [nstbayless/flyweb-mp3#56]
Whenever I want to scroll down on the page, I keep accidentally dragging a song and re-ordering it. A better solution would be to have handles that I can hold and drag.

**Comment by nstbayless** [comment]
That could work. The way Google Play does it is by long-pressing before
drag.

**Comment by wchae** [comment]
Addressed in the frontend-refactor branch

**Comment by wchae** [comment]
Fixed in https://github.com/nstbayless/flyweb-mp3/commit/8efcb6bbb510ea347b7d96042bbc99f04a88643e
