### ISSUE TITLE
Database functionality

### ISSUE THREAD

**Issue by nstbayless** [nstbayless/flyweb-mp3#6]
@joshvazquez As a front-end developer, I want these functions:
- getPlaylist(plid), where plid is something URL-safe, like "q" or "playlist-1".
  - returns playlist {name: "a name",song_list: [(list of song ids)]}
- getSong(sid), where sid is a number.
  - returns song {name: "name", filename: "uploads/blah.mp3", etc.}
- chooseSong(plid,sid)
  - starts playing a song... @wchae and @sinoforever might need to give input on this.
- nextSong(plid,sid)
  - returns the song after the given song on the playlist, possibly null. (perhaps playlist can loop, or shuffle? ... think about this later)
- appendSong(plid,sid): adds song to playlist; adds playlist if it doesn't exist
- rearrangeSongs(plid,list_of_sid), changes song list to be this; adds playlist if it doesn't exist
- deletePlaylist(plid), drops the given playlist

**Comment by joshvazquez** [comment]
Wrote most of these functions for in-memory playlists. Persistent storage to be added.

**Comment by nstbayless** [comment]
Here's another method we need:
removeSong(plid, sid), where sid is a number.
 - removes the song at the given index in the playlist from the given playlist

**Comment by joshvazquez** [comment]
Since use case is not persistent playlists, will stick with in-memory lists instead of using a database. Closing.
